# Generated by Django 3.2.7 on 2022-12-06 13:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_objects_probe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='fiber_composition_description2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Целлюлоза сульфитная'), (2, 'Целлюлоза сульфатная'), (3, 'Лён'), (4, 'Хлопок'), (5, 'Конопля')], max_length=5, null=True, verbose_name='Состав по волокну'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='filigree_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Филигрань рисунок'),
        ),
    ]
