# Generated by Django 3.2.7 on 2022-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20221206_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='filigree_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Филигрань рисунок'),
        ),
    ]
