# Generated by Django 3.2.7 on 2022-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_objects_filigree_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='filigree_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание филигра  ни'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='filigree_pic',
            field=models.ImageField(blank=True, null=True, upload_to='news/media/images/', verbose_name='Филигрань рисунок'),
        ),
    ]
