# Generated by Django 3.2.7 on 2022-12-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20221208_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='date_of_form',
            field=models.DateField(blank=True, verbose_name='Дата отливочной формы'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='eds_composition',
            field=models.JSONField(blank=True, null=True, verbose_name='ЭДС количественые значения'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='filigree_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Филигрань рисунок'),
        ),
    ]
