# Generated by Django 3.2.7 on 2022-12-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20221215_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objects',
            name='rfa_composition',
        ),
    ]
