# Generated by Django 3.2.7 on 2022-12-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_objects_rfa_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='rfa_composition',
            field=models.JSONField(blank=True, null=True, verbose_name='РФА количественые значения'),
        ),
    ]
