# Generated by Django 3.2.7 on 2022-12-22 14:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_objects_rfa_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objects',
            name='title',
        ),
        migrations.AlterField(
            model_name='objects',
            name='date_of_form',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отливочной формы'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='eds_composition',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='ЭДС количественые значения'),
        ),
    ]
