# Generated by Django 3.2.7 on 2023-01-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20221222_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='IRFourier_description',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='ИК-Фурье описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='IRFourier_exp_data',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='ИК-Фурье (параметры измерений)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='Literature',
            field=models.TextField(blank=True, default=1, verbose_name='Литература'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='countermark_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images_count/', verbose_name='Контрмарка рисунок'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='detailed_description',
            field=models.TextField(blank=True, default=1, verbose_name='Подробное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='eds_exp_data',
            field=models.CharField(blank=True, default=11, max_length=250, verbose_name='ЭДС (параметры измерений)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='esm_exp_data',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='СЭМ (параметры измерений)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='notes',
            field=models.TextField(blank=True, default=1, verbose_name='Примечания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='pH_exp',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='pH (параметры измерений)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='polmic_param',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='Поляризационная микроскопия, параметры измерений'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='rfa_exp_data',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='РФА (параметры измерений)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objects',
            name='whiteness_exp',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='Белизна (параметры измерений)'),
            preserve_default=False,
        ),
    ]
