# Generated by Django 3.2.7 on 2023-02-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_imageobjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageObjects',
        ),
    ]
