# Generated by Django 3.2.7 on 2023-02-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_delete_imageobjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='filigree_bernstein',
            field=models.URLField(blank=True, max_length=250, verbose_name='Филигрань Бернштейн'),
        ),
    ]
