# Generated by Django 3.2.7 on 2023-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_objects_filigree_bernstein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='eds_composition',
            field=models.JSONField(blank=True, null=True, verbose_name='ЭДС количественые значения'),
        ),
    ]
