# Generated by Django 3.2.7 on 2023-02-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_objects_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
