# Generated by Django 3.2.7 on 2023-02-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_objectimage_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectimage',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.objects'),
        ),
    ]
