# Generated by Django 3.2.7 on 2023-02-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_objectimage_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectimage',
            name='name',
            field=models.CharField(default='Noname', max_length=100),
            preserve_default=False,
        ),
    ]
