# Generated by Django 3.2.7 on 2023-03-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_objectimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectimage',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.objects'),
        ),
        migrations.CreateModel(
            name='Filpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='try_fil_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='news.objects')),
            ],
        ),
    ]
