# Generated by Django 3.2.7 on 2023-03-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20230320_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectImage',
        ),
    ]
