# Generated by Django 3.2.7 on 2023-03-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_delete_objectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filpic',
            name='image',
            field=models.ImageField(upload_to='fil_image/'),
        ),
        migrations.AlterField(
            model_name='filpic',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filimgs', to='news.objects'),
        ),
        migrations.CreateModel(
            name='Countpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='count_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countimgs', to='news.objects')),
            ],
        ),
    ]
