# Generated by Django 3.2.7 on 2023-03-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20230328_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfaSpecImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rfa_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfaimgs', to='news.objects')),
            ],
        ),
        migrations.CreateModel(
            name='PolmicPolImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pol_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polimicpolimgs', to='news.objects')),
            ],
        ),
        migrations.CreateModel(
            name='PolimicCrossImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cross_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polimiccrossimgs', to='news.objects')),
            ],
        ),
        migrations.CreateModel(
            name='IRFurImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fourier_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irfourierimgs', to='news.objects')),
            ],
        ),
        migrations.CreateModel(
            name='FiberHercImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='herc_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiberhercimgs', to='news.objects')),
            ],
        ),
        migrations.CreateModel(
            name='FiberGraffImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='graff_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fibergraffimgs', to='news.objects')),
            ],
        ),
        migrations.CreateModel(
            name='EsmSecImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='esmsec_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esmsecimgs', to='news.objects')),
            ],
        ),
        migrations.CreateModel(
            name='EsmRevImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='esmrev_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esmrevimgs', to='news.objects')),
            ],
        ),
        migrations.CreateModel(
            name='EdsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='eds_image/')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edsimgs', to='news.objects')),
            ],
        ),
    ]
