# Generated by Django 3.2.7 on 2023-04-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_edsimg_esmrevimg_esmsecimg_fibergraffimg_fiberhercimg_irfurimg_polimiccrossimg_polmicpolimg_rfaspeci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irfurimg',
            name='image',
            field=models.FileField(upload_to='fourier_image/'),
        ),
    ]
