# Generated by Django 3.2.7 on 2023-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_alter_irfurimg_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objects',
            name='IRFourier_pic',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='countermark_pic',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='eds',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='esm_reverse_pic',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='esm_second_pic',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='fiber_composition_graff',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='fiber_composition_herc',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='filigree_pic',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='polmic_cross',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='polmic_pol',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='rfa_spectrum',
        ),
        migrations.AlterField(
            model_name='countpic',
            name='image',
            field=models.ImageField(upload_to='count_image/', verbose_name='Контрмарка рисунок'),
        ),
        migrations.AlterField(
            model_name='edsimg',
            name='image',
            field=models.ImageField(upload_to='eds_image/', verbose_name='ЭДС рисунок спектра'),
        ),
        migrations.AlterField(
            model_name='esmrevimg',
            name='image',
            field=models.ImageField(upload_to='esmrev_image/', verbose_name='СЭМ обратно рассеянные'),
        ),
        migrations.AlterField(
            model_name='esmsecimg',
            name='image',
            field=models.ImageField(upload_to='esmsec_image/', verbose_name='СЭМ вторичные электроны'),
        ),
        migrations.AlterField(
            model_name='fibergraffimg',
            name='image',
            field=models.ImageField(upload_to='graff_image/', verbose_name='Состав по волокну (Графф)'),
        ),
        migrations.AlterField(
            model_name='fiberhercimg',
            name='image',
            field=models.ImageField(upload_to='herc_image/', verbose_name='Состав по волокну (Херцберг)'),
        ),
        migrations.AlterField(
            model_name='filpic',
            name='image',
            field=models.ImageField(upload_to='fil_image/', verbose_name='Филигрань рисунок'),
        ),
        migrations.AlterField(
            model_name='irfurimg',
            name='image',
            field=models.FileField(upload_to='fourier_image/', verbose_name='ИК-Фурье рисунок'),
        ),
        migrations.AlterField(
            model_name='polimiccrossimg',
            name='image',
            field=models.ImageField(upload_to='cross_image/', verbose_name='Поляризационная микроскопия в скрещенных николях'),
        ),
        migrations.AlterField(
            model_name='polmicpolimg',
            name='image',
            field=models.ImageField(upload_to='pol_image/', verbose_name='Поляризационная микроскопия в поляризованном свете'),
        ),
        migrations.AlterField(
            model_name='rfaspecimg',
            name='image',
            field=models.ImageField(upload_to='rfa_image/', verbose_name='Рисунок спектра РФА'),
        ),
    ]
