# Generated by Django 3.2.7 on 2023-04-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20230406_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countpic',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='edsimg',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edsimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='esmrevimg',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esmrevimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='esmsecimg',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esmsecimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='fibergraffimg',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fibergraffimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='fiberhercimg',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiberhercimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='filpic',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='irfurimg',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irfourierimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='polimiccrossimg',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polimiccrossimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='polmicpolimg',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polimicpolimgs', to='news.objects'),
        ),
        migrations.AlterField(
            model_name='rfaspecimg',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfaimgs', to='news.objects'),
        ),
    ]
