# Generated by Django 3.2.7 on 2023-04-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20230413_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='filigree',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Да'), (2, 'Нет')], null=True, verbose_name='Наличие филиграни'),
        ),
        migrations.AddField(
            model_name='objects',
            name='stamp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Да'), (2, 'Нет')], null=True, verbose_name='Наличие штемпеля'),
        ),
        migrations.AddField(
            model_name='objects',
            name='stamp_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание штемпеля'),
        ),
        migrations.AddField(
            model_name='objects',
            name='stamp_purpose',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Гербовая бумага'), (2, 'Производственный знак'), (3, 'Личный знак')], null=True, verbose_name='Назначение штемпеля'),
        ),
        migrations.AddField(
            model_name='objects',
            name='stamp_tec',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Слепое тиснение'), (2, 'Золотое тиснение'), (3, 'Окрашенный оттиск')], null=True, verbose_name='Штемпель техника'),
        ),
        migrations.CreateModel(
            name='Stamppic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stamp_image/', verbose_name='Штемпель фото')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stampimgs', to='news.objects')),
            ],
        ),
    ]
